version: '3.4'

services:

  universitydb:
    container_name: universitydb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  sqlpad:
    container_name: sqlpad
    environment:
      - SQLPAD_ADMIN=admin@sqlpad.com
      - SQLPAD_ADMIN_PASSWORD=83Wrw50
    restart: always
    volumes:
      - sqlpad_data:/var/lib/sqlpad
    ports:
      - "3000:3000"


  cleanarchitecture.mvc:
    container_name: cleanarchitecture.mvc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro